### ISSUE TITLE
curl実装

### ISSUE THREAD

**Issue by kurupeku** [kurupeku/go-swiss-army-knives#2]
- [ ] GET / POST / PUT / PATCH / DELETE 対応
- [ ] クエリパラメータのエンコード
- [ ] ヘッダー
- [ ] ボディ（JSON）

**Comment by kudagonbe** [comment]
@kurupeku 
一旦PRを出しました。READMEがまだ書き途中ですが、現時点で気になるところあれば指摘もらえると嬉しいです！
https://github.com/kurupeku/go-swiss-army-knives/pull/5

**Comment by kurupeku** [comment]
完成！
@kudagonbe 作成ありがとうございました！
